teleportCooldown: 60
teleportDelay: 5
teleportInvulnerability: 5
healCooldown: 60
allowAfk: true
autoAfk: 300
autoAfkKick: 2800
autoSaveInterval: 300
tpAcceptCancellation: 30
startingBalance: 1000.0
minMoney: 0.0
maxMoney: 9.99999999E8
minPayAmount: 1.0
payCooldown: 15
