teleportCooldown: 60
teleportDelay: 5
teleportInvulnerability: 5
healCooldown: 60
allowAfk: true
autoAfk: 300
autoAfkKick: 2800
autoSaveInterval: 300
tpAcceptCancellation: 30
startingBalance: 1000
minMoney: 0
maxMoney: 999999999
minPayAmount: 1
payCooldown: 15
